{% set name = "libical" %}
{% set version = "3.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 09fecacaf75ba5a242159e3a9758a5446b5ce4d0ab684f98a7040864e1d1286f

build:
  number: 2
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libical', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - cmake >=3.11.0
    - perl
    - pkg-config  # [osx]
  host:
    - icu
    - glib
    - libxml2
    - gobject-introspection  # [linux]
  run:
    - {{ pin_compatible("gobject-introspection", max_pin="x.x") }}  # [linux]

test:
  commands:
    - test -f "${PREFIX}/lib/libical${SHLIB_EXT}"

about:
  home: http://libical.github.io/libical/
  license: MPL v2
  license_family: OTHER
  license_file: LICENSE.MPL2.txt
  summary: An Open Source implementation of the iCalendar protocols and protocol data units
  description: |
    Libical is an Open Source implementation of the iCalendar protocols and protocol data units.
    The iCalendar specification describes how calendar clients can communicate with calendar
    servers so users can store their calendar data and arrange meetings with other users.
    Libical implements RFC2445, RFC2446 and some of RFC2447.
  doc_url: http://libical.github.io/libical/
  dev_url: https://github.com/libical/libical

extra:
  recipe-maintainers:
    - scopatz
