{% set name = "libical" %}
{% set version = "3.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 35095a4cc1a061a3de0f332c2dc728226cf127fa0baa818e9f8856cee6d35830

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libical', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - cmake >=3.11.0
    - perl
    - pkg-config  # [osx]
  host:
    - icu
    - glib
    - libxml2
    - gobject-introspection  # [linux]
  run:
    - {{ pin_compatible("gobject-introspection", max_pin="x.x") }}  # [linux]

test:
  commands:
    - test -f "${PREFIX}/lib/libical${SHLIB_EXT}"

about:
  home: http://libical.github.io/libical/
  license: MPL v2
  license_family: OTHER
  license_file: LICENSE.MPL2.txt
  summary: An Open Source implementation of the iCalendar protocols and protocol data units
  description: |
    Libical is an Open Source implementation of the iCalendar protocols and protocol data units.
    The iCalendar specification describes how calendar clients can communicate with calendar
    servers so users can store their calendar data and arrange meetings with other users.
    Libical implements RFC2445, RFC2446 and some of RFC2447.
  doc_url: http://libical.github.io/libical/
  dev_url: https://github.com/libical/libical

extra:
  recipe-maintainers:
    - scopatz
