travis:
  secure:
    BINSTAR_TOKEN: ujc2fzerHdIYkq0SfB7BJQLvFAomsDMSEql+qPQjL8nJJ6KqRlyQ5OjXYIRw0HJkY74AIH7AFocRvdf0UAgXt65DnqYyPaTPfE+HmuSGbAmOBV6tOJTQ3wj8Jd4RYbmvVP2Ts/OXtR4r2fsMwOwahAXe2NWD+ntejw7MKxFjl9BWDeuoVcfM6eJPZ0pAOFwXFhl3/RQLJV2yZG6zHueGzKRcl9P56tYnqVUXPJg1iyQaN7lUswn+F9BbDYyQi5wxpBG1g4Qcb5ZUxpNblemKCFydW68a96au21Vr8Uw1+q82qiSBMxzrPsuZdbqJVAPpYpF34Pn6Pz9DNog3AvnuunVQ6Y2bJFp47a74D3PrYSNUCEsqWY+PIrY0wvSSmm7RQ2IVZKr+W3UZ8Jur4UBhMYf9gYmLn4+XBnqkvUhE/KdpWPl0pZ+TDg+IP1cSVs79AZc+vuD5gfMk7FV6utb3B/zbBR2EdSOA3QowPQ4DYgJDYYcV1N7OEDUS6CORgo1JWrnHHQ1T7QQnFHBHmPXrSrxxIhOq2JH3DCGkGxOdA/3elNE5N/g+hkNKn/J1oJ3L9rlLnwkQHXuxLf7cUfljRSBhFT7wdT2L0RB681+VqhbHqKSUP69F2sb5uTAyf7DktoKnDfJ7fgBlN9gdBixwUhcsHYbzfGGIhZL/wiU8Nzc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
